intents = {
    "rating: [
        "rating",
        "overall score",
        "rated",
        "rate",
        "scoring",
        "score",
        "review",
        "reviewed",
        "excellent",
        "great",
        "very good",
        "good",
        "average",
        "poor",
    ],
    "location": [
        "location",
        "city",
        "country",
        "hotels in",
        "properties in",
        "accommodation in",
        "where",
        "which city",
        "which country",
        "geographic location",
    ],
    "visa": [
        "visa",
        "visa required",
        "visa not required",
        "visa needed",
        "need visa",
        "visa free",
        "visa exempt",
        "visa waiver",
        "visa on arrival",
        "evisa",
        "e-visa",
        "tourist visa",
        "travel visa",
        "visa type",
        "visa requirements",
        "visa information",
        "no visa",
    ],
    "demographics": [
        "age",
        "gender",
        "male travellers",
        "female travellers",
    ],
    "cleanliness": [
        "cleanliness",
        "clean",
        "tidy",
        "neat",
        "orderly",
        "spotless",
        "immaculate",
        "hygienic",
        "sanitary",
        "spick and span",
        "sterile",
        "fresh",
        "pristine",
        "well-kept",
        "unsoiled",
        "unsullied",
        "scrubbed",
        "dirt-free",
        "germ-free",
    ],
    "comfort": [
        "comfort",
        "comfortable",
        "peaceful",
        "cosy",
        "cozy",
        "snug",
        "relaxing",
        "restful",
        "at ease",
        "soothing",
        "comfy",
        "plush",
        "soft",
        "luxurious",
        "easygoing",
        "snuggly",
    ],
    "facilities": [
        "facilities",
        "facility",
        "amenities",
        "amenity",
        "features",
        "facility rating",
        "facility score",
        "amenity rating",
        "amenity score",
        "hotel facility",
        "hotel facilities",
        "property facilities",
        "property amenity",
        "infrastructure",
        "services",
        "accommodation features",
    ],
    "value_for_money": [
        "value for money",
        "value",
        "worth",
        "price",
        "cost",
        "bang for buck",
        "price-quality",
        "money's worth",
        "reasonable price",
        "good value",
        "spending",
        "financial value",
        "cost effectiveness",
        "cost-efficient",
        "cost-benefit",
    ],
    "location_rating": [
        "location rating",
        "location score",
        "well located",
        "convenient location",
        "accessibility",
    ],
    "staff": [
        "staff",
        "service",
        "customer service",
        "helpful staff",
        "friendly staff",
        "staff rating",
        "staff score",
        "employees",
        "personnel",
        "hospitality",
        "polite staff",
    ],
}

__all__ = ["intents"]
